"""Regenerate backend/app/quran_metadata.py for all 114 surahs.

The file used to cover fifteen surahs, deliberately: it described what the
Rattil audio repository actually held, and claiming more would have made the
API promise recitations it could not serve. Now that a reciter's complete Quran
is available, the ayah counts and names have to cover all of it -- but
availability is still per reciter, and is decided by the `availableSurahs`
field on each qari, not by this file.

Generated from frontend/assets/quran/quran_full.json, which is the same text the
app displays, so the backend cannot drift from what the user is reading.

    backend/.venv/Scripts/python.exe ml/tools/generate_quran_metadata.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
SOURCE = REPO / "frontend" / "assets" / "quran" / "quran_full.json"
TARGET = REPO / "backend" / "app" / "quran_metadata.py"

HEADER = '''"""Surah names and ayah counts for all 114 surahs.

Generated by ml/tools/generate_quran_metadata.py from the same Quran asset the
app renders (frontend/assets/quran/quran_full.json), so the two cannot drift.

This file says what the Quran contains, not what the server can play. Which
surahs a given reciter has audio for is a property of that reciter and lives on
the `availableSurahs` field of the qari record -- an earlier version of this file
conflated the two, which is why it stopped at the fifteen surahs that happened to
have recordings at the time.
"""
'''


def main() -> int:
    data = json.loads(SOURCE.read_text(encoding="utf-8"))
    surahs = data["surahs"]
    if len(surahs) != 114:
        print(f"Expected 114 surahs in {SOURCE}, found {len(surahs)}")
        return 1

    counts: dict[int, int] = {}
    names: dict[int, dict] = {}
    for s in surahs:
        number = int(s["number"])
        ayahs = s["ayahs"]
        if isinstance(ayahs, str):
            # The asset stores the ayah list as a repr-like string in places;
            # counting entries is enough and avoids trusting a fragile parse.
            count = ayahs.count("'number':")
        else:
            count = len(ayahs)
        if count <= 0:
            print(f"Surah {number} has no ayahs in the source asset")
            return 1
        counts[number] = count
        names[number] = {
            "arabic": s["nameArabic"],
            "english": s["nameEnglish"],
            "meaning": s.get("meaning", ""),
        }

    total = sum(counts.values())
    if total != 6236:
        print(f"Ayah total came out at {total}, expected 6236 -- refusing to write")
        return 1

    lines = [HEADER, "", "SURAH_AYAH_COUNTS = {"]
    for n in range(1, 115):
        lines.append(f"    {n}: {counts[n]},")
    lines.append("}")
    lines.append("")
    lines.append("SURAH_NAMES = {")
    for n in range(1, 115):
        entry = names[n]
        lines.append(
            f'    {n}: {{"arabic": {entry["arabic"]!r}, '
            f'"english": {entry["english"]!r}, '
            f'"meaning": {entry["meaning"]!r}}},'
        )
    lines.append("}")
    lines.append("")

    TARGET.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {TARGET}: 114 surahs, {total} ayahs")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
