import '../models/surah.dart';

/// Complete 114-Surah dataset. Scores on commonly practiced surahs are
/// pre-populated so the practiced-% badge shows in the Explore list.
/// Replace with real backend data in a later phase.
final List<Surah> dummySurahs = [
  const Surah(number: 1,   nameArabic: 'الفاتحة',    nameEnglish: 'Al-Fatihah',     meaning: 'The Opening',                  ayahCount: 7,   revelationPlace: 'Makkah',   lastScore: 92, isBookmarked: true),
  const Surah(number: 2,   nameArabic: 'البقرة',      nameEnglish: 'Al-Baqarah',     meaning: 'The Cow',                       ayahCount: 286, revelationPlace: 'Madinah',  lastScore: 78),
  const Surah(number: 3,   nameArabic: 'آل عمران',    nameEnglish: 'Aal-E-Imran',    meaning: 'The Family of Imran',           ayahCount: 200, revelationPlace: 'Madinah',  lastScore: 62),
  const Surah(number: 4,   nameArabic: 'النساء',      nameEnglish: 'An-Nisa',        meaning: 'The Women',                     ayahCount: 176, revelationPlace: 'Madinah'),
  const Surah(number: 5,   nameArabic: 'المائدة',     nameEnglish: "Al-Ma'idah",     meaning: 'The Table Spread',              ayahCount: 120, revelationPlace: 'Madinah'),
  const Surah(number: 6,   nameArabic: 'الأنعام',     nameEnglish: "Al-An'am",       meaning: 'The Cattle',                    ayahCount: 165, revelationPlace: 'Makkah'),
  const Surah(number: 7,   nameArabic: 'الأعراف',     nameEnglish: "Al-A'raf",       meaning: 'The Heights',                   ayahCount: 206, revelationPlace: 'Makkah'),
  const Surah(number: 8,   nameArabic: 'الأنفال',     nameEnglish: 'Al-Anfal',       meaning: 'The Spoils of War',             ayahCount: 75,  revelationPlace: 'Madinah'),
  const Surah(number: 9,   nameArabic: 'التوبة',      nameEnglish: 'At-Tawbah',      meaning: 'The Repentance',                ayahCount: 129, revelationPlace: 'Madinah'),
  const Surah(number: 10,  nameArabic: 'يونس',        nameEnglish: 'Yunus',          meaning: 'Jonah',                         ayahCount: 109, revelationPlace: 'Makkah'),
  const Surah(number: 11,  nameArabic: 'هود',         nameEnglish: 'Hud',            meaning: 'Hud',                           ayahCount: 123, revelationPlace: 'Makkah'),
  const Surah(number: 12,  nameArabic: 'يوسف',        nameEnglish: 'Yusuf',          meaning: 'Joseph',                        ayahCount: 111, revelationPlace: 'Makkah'),
  const Surah(number: 13,  nameArabic: 'الرعد',       nameEnglish: "Ar-Ra'd",        meaning: 'The Thunder',                   ayahCount: 43,  revelationPlace: 'Madinah'),
  const Surah(number: 14,  nameArabic: 'ابراهيم',     nameEnglish: 'Ibrahim',        meaning: 'Abraham',                       ayahCount: 52,  revelationPlace: 'Makkah'),
  const Surah(number: 15,  nameArabic: 'الحجر',       nameEnglish: 'Al-Hijr',        meaning: 'The Rocky Tract',               ayahCount: 99,  revelationPlace: 'Makkah'),
  const Surah(number: 16,  nameArabic: 'النحل',       nameEnglish: 'An-Nahl',        meaning: 'The Bee',                       ayahCount: 128, revelationPlace: 'Makkah'),
  const Surah(number: 17,  nameArabic: 'الإسراء',     nameEnglish: 'Al-Isra',        meaning: 'The Night Journey',             ayahCount: 111, revelationPlace: 'Makkah'),
  const Surah(number: 18,  nameArabic: 'الكهف',       nameEnglish: 'Al-Kahf',        meaning: 'The Cave',                      ayahCount: 110, revelationPlace: 'Makkah',   lastScore: 85, isBookmarked: true),
  const Surah(number: 19,  nameArabic: 'مريم',        nameEnglish: 'Maryam',         meaning: 'Mary',                          ayahCount: 98,  revelationPlace: 'Makkah'),
  const Surah(number: 20,  nameArabic: 'طه',          nameEnglish: 'Ta-Ha',          meaning: 'Ta-Ha',                         ayahCount: 135, revelationPlace: 'Makkah'),
  const Surah(number: 21,  nameArabic: 'الأنبياء',    nameEnglish: 'Al-Anbiya',      meaning: 'The Prophets',                  ayahCount: 112, revelationPlace: 'Makkah'),
  const Surah(number: 22,  nameArabic: 'الحج',        nameEnglish: 'Al-Hajj',        meaning: 'The Pilgrimage',                ayahCount: 78,  revelationPlace: 'Madinah'),
  const Surah(number: 23,  nameArabic: 'المؤمنون',    nameEnglish: "Al-Mu'minun",    meaning: 'The Believers',                 ayahCount: 118, revelationPlace: 'Makkah'),
  const Surah(number: 24,  nameArabic: 'النور',       nameEnglish: 'An-Nur',         meaning: 'The Light',                     ayahCount: 64,  revelationPlace: 'Madinah'),
  const Surah(number: 25,  nameArabic: 'الفرقان',     nameEnglish: 'Al-Furqan',      meaning: 'The Criterion',                 ayahCount: 77,  revelationPlace: 'Makkah'),
  const Surah(number: 26,  nameArabic: 'الشعراء',     nameEnglish: "Ash-Shu'ara",    meaning: 'The Poets',                     ayahCount: 227, revelationPlace: 'Makkah'),
  const Surah(number: 27,  nameArabic: 'النمل',       nameEnglish: 'An-Naml',        meaning: 'The Ant',                       ayahCount: 93,  revelationPlace: 'Makkah'),
  const Surah(number: 28,  nameArabic: 'القصص',       nameEnglish: 'Al-Qasas',       meaning: 'The Stories',                   ayahCount: 88,  revelationPlace: 'Makkah'),
  const Surah(number: 29,  nameArabic: 'العنكبوت',    nameEnglish: 'Al-Ankabut',     meaning: 'The Spider',                    ayahCount: 69,  revelationPlace: 'Makkah'),
  const Surah(number: 30,  nameArabic: 'الروم',       nameEnglish: 'Ar-Rum',         meaning: 'The Romans',                    ayahCount: 60,  revelationPlace: 'Makkah'),
  const Surah(number: 31,  nameArabic: 'لقمان',       nameEnglish: 'Luqman',         meaning: 'Luqman',                        ayahCount: 34,  revelationPlace: 'Makkah'),
  const Surah(number: 32,  nameArabic: 'السجدة',      nameEnglish: 'As-Sajdah',      meaning: 'The Prostration',               ayahCount: 30,  revelationPlace: 'Makkah'),
  const Surah(number: 33,  nameArabic: 'الأحزاب',     nameEnglish: 'Al-Ahzab',       meaning: 'The Combined Forces',           ayahCount: 73,  revelationPlace: 'Madinah'),
  const Surah(number: 34,  nameArabic: 'سبإ',         nameEnglish: 'Saba',           meaning: 'Sheba',                         ayahCount: 54,  revelationPlace: 'Makkah'),
  const Surah(number: 35,  nameArabic: 'فاطر',        nameEnglish: 'Fatir',          meaning: 'Originator',                    ayahCount: 45,  revelationPlace: 'Makkah'),
  const Surah(number: 36,  nameArabic: 'يس',          nameEnglish: 'Ya-Sin',         meaning: 'Ya Sin',                        ayahCount: 83,  revelationPlace: 'Makkah',   lastScore: 88),
  const Surah(number: 37,  nameArabic: 'الصافات',     nameEnglish: 'As-Saffat',      meaning: 'Those Who Set the Ranks',       ayahCount: 182, revelationPlace: 'Makkah'),
  const Surah(number: 38,  nameArabic: 'ص',           nameEnglish: 'Sad',            meaning: 'The Letter Sad',                ayahCount: 88,  revelationPlace: 'Makkah'),
  const Surah(number: 39,  nameArabic: 'الزمر',       nameEnglish: 'Az-Zumar',       meaning: 'The Troops',                    ayahCount: 75,  revelationPlace: 'Makkah'),
  const Surah(number: 40,  nameArabic: 'غافر',        nameEnglish: 'Ghafir',         meaning: 'The Forgiver',                  ayahCount: 85,  revelationPlace: 'Makkah'),
  const Surah(number: 41,  nameArabic: 'فصلت',        nameEnglish: 'Fussilat',       meaning: 'Explained in Detail',           ayahCount: 54,  revelationPlace: 'Makkah'),
  const Surah(number: 42,  nameArabic: 'الشورى',      nameEnglish: 'Ash-Shuraa',     meaning: 'The Consultation',              ayahCount: 53,  revelationPlace: 'Makkah'),
  const Surah(number: 43,  nameArabic: 'الزخرف',      nameEnglish: 'Az-Zukhruf',     meaning: 'The Gold Adornments',           ayahCount: 89,  revelationPlace: 'Makkah'),
  const Surah(number: 44,  nameArabic: 'الدخان',      nameEnglish: 'Ad-Dukhan',      meaning: 'The Smoke',                     ayahCount: 59,  revelationPlace: 'Makkah'),
  const Surah(number: 45,  nameArabic: 'الجاثية',     nameEnglish: 'Al-Jathiyah',    meaning: 'The Crouching',                 ayahCount: 37,  revelationPlace: 'Makkah'),
  const Surah(number: 46,  nameArabic: 'الأحقاف',     nameEnglish: 'Al-Ahqaf',       meaning: 'The Wind-Curved Sandhills',     ayahCount: 35,  revelationPlace: 'Makkah'),
  const Surah(number: 47,  nameArabic: 'محمد',        nameEnglish: 'Muhammad',       meaning: 'Muhammad',                      ayahCount: 38,  revelationPlace: 'Madinah'),
  const Surah(number: 48,  nameArabic: 'الفتح',       nameEnglish: 'Al-Fath',        meaning: 'The Victory',                   ayahCount: 29,  revelationPlace: 'Madinah'),
  const Surah(number: 49,  nameArabic: 'الحجرات',     nameEnglish: 'Al-Hujurat',     meaning: 'The Rooms',                     ayahCount: 18,  revelationPlace: 'Madinah'),
  const Surah(number: 50,  nameArabic: 'ق',           nameEnglish: 'Qaf',            meaning: 'The Letter Qaf',                ayahCount: 45,  revelationPlace: 'Makkah'),
  const Surah(number: 51,  nameArabic: 'الذاريات',    nameEnglish: 'Adh-Dhariyat',   meaning: 'The Winnowing Winds',           ayahCount: 60,  revelationPlace: 'Makkah'),
  const Surah(number: 52,  nameArabic: 'الطور',       nameEnglish: 'At-Tur',         meaning: 'The Mount',                     ayahCount: 49,  revelationPlace: 'Makkah'),
  const Surah(number: 53,  nameArabic: 'النجم',       nameEnglish: 'An-Najm',        meaning: 'The Star',                      ayahCount: 62,  revelationPlace: 'Makkah'),
  const Surah(number: 54,  nameArabic: 'القمر',       nameEnglish: 'Al-Qamar',       meaning: 'The Moon',                      ayahCount: 55,  revelationPlace: 'Makkah'),
  const Surah(number: 55,  nameArabic: 'الرحمن',      nameEnglish: 'Ar-Rahman',      meaning: 'The Beneficent',                ayahCount: 78,  revelationPlace: 'Madinah',  lastScore: 70),
  const Surah(number: 56,  nameArabic: 'الواقعة',     nameEnglish: "Al-Waqi'ah",     meaning: 'The Inevitable',                ayahCount: 96,  revelationPlace: 'Makkah'),
  const Surah(number: 57,  nameArabic: 'الحديد',      nameEnglish: 'Al-Hadid',       meaning: 'The Iron',                      ayahCount: 29,  revelationPlace: 'Madinah'),
  const Surah(number: 58,  nameArabic: 'المجادلة',    nameEnglish: 'Al-Mujadila',    meaning: 'The Pleading Woman',            ayahCount: 22,  revelationPlace: 'Madinah'),
  const Surah(number: 59,  nameArabic: 'الحشر',       nameEnglish: 'Al-Hashr',       meaning: 'The Exile',                     ayahCount: 24,  revelationPlace: 'Madinah'),
  const Surah(number: 60,  nameArabic: 'الممتحنة',    nameEnglish: 'Al-Mumtahanah',  meaning: 'She That Is to Be Examined',    ayahCount: 13,  revelationPlace: 'Madinah'),
  const Surah(number: 61,  nameArabic: 'الصف',        nameEnglish: 'As-Saf',         meaning: 'The Ranks',                     ayahCount: 14,  revelationPlace: 'Madinah'),
  const Surah(number: 62,  nameArabic: 'الجمعة',      nameEnglish: "Al-Jumu'ah",     meaning: 'Friday / The Congregation',     ayahCount: 11,  revelationPlace: 'Madinah'),
  const Surah(number: 63,  nameArabic: 'المنافقون',   nameEnglish: 'Al-Munafiqun',   meaning: 'The Hypocrites',                ayahCount: 11,  revelationPlace: 'Madinah'),
  const Surah(number: 64,  nameArabic: 'التغابن',     nameEnglish: 'At-Taghabun',    meaning: 'The Mutual Disillusion',        ayahCount: 18,  revelationPlace: 'Madinah'),
  const Surah(number: 65,  nameArabic: 'الطلاق',      nameEnglish: 'At-Talaq',       meaning: 'The Divorce',                   ayahCount: 12,  revelationPlace: 'Madinah'),
  const Surah(number: 66,  nameArabic: 'التحريم',     nameEnglish: 'At-Tahrim',      meaning: 'The Prohibition',               ayahCount: 12,  revelationPlace: 'Madinah'),
  const Surah(number: 67,  nameArabic: 'الملك',       nameEnglish: 'Al-Mulk',        meaning: 'The Sovereignty',               ayahCount: 30,  revelationPlace: 'Makkah',   lastScore: 95),
  const Surah(number: 68,  nameArabic: 'القلم',       nameEnglish: 'Al-Qalam',       meaning: 'The Pen',                       ayahCount: 52,  revelationPlace: 'Makkah'),
  const Surah(number: 69,  nameArabic: 'الحاقة',      nameEnglish: 'Al-Haqqah',      meaning: 'The Reality',                   ayahCount: 52,  revelationPlace: 'Makkah'),
  const Surah(number: 70,  nameArabic: 'المعارج',     nameEnglish: "Al-Ma'arij",     meaning: 'The Ascending Stairways',       ayahCount: 44,  revelationPlace: 'Makkah'),
  const Surah(number: 71,  nameArabic: 'نوح',         nameEnglish: 'Nuh',            meaning: 'Noah',                          ayahCount: 28,  revelationPlace: 'Makkah'),
  const Surah(number: 72,  nameArabic: 'الجن',        nameEnglish: 'Al-Jinn',        meaning: 'The Jinn',                      ayahCount: 28,  revelationPlace: 'Makkah'),
  const Surah(number: 73,  nameArabic: 'المزمل',      nameEnglish: 'Al-Muzzammil',   meaning: 'The Enshrouded One',            ayahCount: 20,  revelationPlace: 'Makkah'),
  const Surah(number: 74,  nameArabic: 'المدثر',      nameEnglish: 'Al-Muddaththir', meaning: 'The Cloaked One',               ayahCount: 56,  revelationPlace: 'Makkah'),
  const Surah(number: 75,  nameArabic: 'القيامة',     nameEnglish: 'Al-Qiyamah',     meaning: 'The Resurrection',              ayahCount: 40,  revelationPlace: 'Makkah'),
  const Surah(number: 76,  nameArabic: 'الانسان',     nameEnglish: 'Al-Insan',       meaning: 'Man / Time',                    ayahCount: 31,  revelationPlace: 'Madinah'),
  const Surah(number: 77,  nameArabic: 'المرسلات',    nameEnglish: 'Al-Mursalat',    meaning: 'The Emissaries',                ayahCount: 50,  revelationPlace: 'Makkah'),
  const Surah(number: 78,  nameArabic: 'النبإ',       nameEnglish: 'An-Naba',        meaning: 'The Tidings',                   ayahCount: 40,  revelationPlace: 'Makkah'),
  const Surah(number: 79,  nameArabic: 'النازعات',    nameEnglish: "An-Nazi'at",     meaning: 'Those Who Drag Forth',          ayahCount: 46,  revelationPlace: 'Makkah'),
  const Surah(number: 80,  nameArabic: 'عبس',         nameEnglish: "'Abasa",         meaning: 'He Frowned',                    ayahCount: 42,  revelationPlace: 'Makkah'),
  const Surah(number: 81,  nameArabic: 'التكوير',     nameEnglish: 'At-Takwir',      meaning: 'The Overthrowing',              ayahCount: 29,  revelationPlace: 'Makkah'),
  const Surah(number: 82,  nameArabic: 'الإنفطار',    nameEnglish: 'Al-Infitar',     meaning: 'The Cleaving',                  ayahCount: 19,  revelationPlace: 'Makkah'),
  const Surah(number: 83,  nameArabic: 'المطففين',    nameEnglish: 'Al-Mutaffifin',  meaning: 'The Defrauding',                ayahCount: 36,  revelationPlace: 'Makkah'),
  const Surah(number: 84,  nameArabic: 'الإنشقاق',    nameEnglish: 'Al-Inshiqaq',    meaning: 'The Sundering',                 ayahCount: 25,  revelationPlace: 'Makkah'),
  const Surah(number: 85,  nameArabic: 'البروج',      nameEnglish: 'Al-Buruj',       meaning: 'The Constellations',            ayahCount: 22,  revelationPlace: 'Makkah'),
  const Surah(number: 86,  nameArabic: 'الطارق',      nameEnglish: 'At-Tariq',       meaning: 'The Morning Star',              ayahCount: 17,  revelationPlace: 'Makkah'),
  const Surah(number: 87,  nameArabic: 'الأعلى',      nameEnglish: "Al-A'la",        meaning: 'The Most High',                 ayahCount: 19,  revelationPlace: 'Makkah'),
  const Surah(number: 88,  nameArabic: 'الغاشية',     nameEnglish: 'Al-Ghashiyah',   meaning: 'The Overwhelming',              ayahCount: 26,  revelationPlace: 'Makkah'),
  const Surah(number: 89,  nameArabic: 'الفجر',       nameEnglish: 'Al-Fajr',        meaning: 'The Dawn',                      ayahCount: 30,  revelationPlace: 'Makkah'),
  const Surah(number: 90,  nameArabic: 'البلد',       nameEnglish: 'Al-Balad',       meaning: 'The City',                      ayahCount: 20,  revelationPlace: 'Makkah'),
  const Surah(number: 91,  nameArabic: 'الشمس',       nameEnglish: 'Ash-Shams',      meaning: 'The Sun',                       ayahCount: 15,  revelationPlace: 'Makkah'),
  const Surah(number: 92,  nameArabic: 'الليل',       nameEnglish: 'Al-Layl',        meaning: 'The Night',                     ayahCount: 21,  revelationPlace: 'Makkah'),
  const Surah(number: 93,  nameArabic: 'الضحى',       nameEnglish: 'Ad-Dhuha',       meaning: 'The Morning Hours',             ayahCount: 11,  revelationPlace: 'Makkah'),
  const Surah(number: 94,  nameArabic: 'الشرح',       nameEnglish: 'Ash-Sharh',      meaning: 'The Relief',                    ayahCount: 8,   revelationPlace: 'Makkah'),
  const Surah(number: 95,  nameArabic: 'التين',       nameEnglish: 'At-Tin',         meaning: 'The Fig',                       ayahCount: 8,   revelationPlace: 'Makkah'),
  const Surah(number: 96,  nameArabic: 'العلق',       nameEnglish: "Al-'Alaq",       meaning: 'The Clot',                      ayahCount: 19,  revelationPlace: 'Makkah'),
  const Surah(number: 97,  nameArabic: 'القدر',       nameEnglish: 'Al-Qadr',        meaning: 'The Power / Fate',              ayahCount: 5,   revelationPlace: 'Makkah'),
  const Surah(number: 98,  nameArabic: 'البينة',      nameEnglish: 'Al-Bayyinah',    meaning: 'The Clear Proof',               ayahCount: 8,   revelationPlace: 'Madinah'),
  const Surah(number: 99,  nameArabic: 'الزلزلة',     nameEnglish: 'Az-Zalzalah',    meaning: 'The Earthquake',                ayahCount: 8,   revelationPlace: 'Madinah'),
  const Surah(number: 100, nameArabic: 'العاديات',    nameEnglish: "Al-'Adiyat",     meaning: 'The Courser',                   ayahCount: 11,  revelationPlace: 'Makkah'),
  const Surah(number: 101, nameArabic: 'القارعة',     nameEnglish: "Al-Qari'ah",     meaning: 'The Calamity',                  ayahCount: 11,  revelationPlace: 'Makkah'),
  const Surah(number: 102, nameArabic: 'التكاثر',     nameEnglish: 'At-Takathur',    meaning: 'The Rivalry in World Increase', ayahCount: 8,   revelationPlace: 'Makkah'),
  const Surah(number: 103, nameArabic: 'العصر',       nameEnglish: "Al-'Asr",        meaning: 'The Declining Day',             ayahCount: 3,   revelationPlace: 'Makkah'),
  const Surah(number: 104, nameArabic: 'الهمزة',      nameEnglish: 'Al-Humazah',     meaning: 'The Traducer',                  ayahCount: 9,   revelationPlace: 'Makkah'),
  const Surah(number: 105, nameArabic: 'الفيل',       nameEnglish: 'Al-Fil',         meaning: 'The Elephant',                  ayahCount: 5,   revelationPlace: 'Makkah'),
  const Surah(number: 106, nameArabic: 'قريش',        nameEnglish: 'Quraysh',        meaning: 'Quraysh',                       ayahCount: 4,   revelationPlace: 'Makkah'),
  const Surah(number: 107, nameArabic: 'الماعون',     nameEnglish: "Al-Ma'un",       meaning: 'The Small Kindnesses',          ayahCount: 7,   revelationPlace: 'Makkah'),
  const Surah(number: 108, nameArabic: 'الكوثر',      nameEnglish: 'Al-Kawthar',     meaning: 'The Abundance',                 ayahCount: 3,   revelationPlace: 'Makkah'),
  const Surah(number: 109, nameArabic: 'الكافرون',    nameEnglish: 'Al-Kafirun',     meaning: 'The Disbelievers',              ayahCount: 6,   revelationPlace: 'Makkah'),
  const Surah(number: 110, nameArabic: 'النصر',       nameEnglish: 'An-Nasr',        meaning: 'The Divine Support',            ayahCount: 3,   revelationPlace: 'Madinah'),
  const Surah(number: 111, nameArabic: 'المسد',       nameEnglish: 'Al-Masad',       meaning: 'The Palm Fiber',                ayahCount: 5,   revelationPlace: 'Makkah'),
  const Surah(number: 112, nameArabic: 'الإخلاص',     nameEnglish: 'Al-Ikhlas',      meaning: 'The Sincerity',                 ayahCount: 4,   revelationPlace: 'Makkah',   lastScore: 97),
  const Surah(number: 113, nameArabic: 'الفلق',       nameEnglish: 'Al-Falaq',       meaning: 'The Daybreak',                  ayahCount: 5,   revelationPlace: 'Makkah'),
  const Surah(number: 114, nameArabic: 'الناس',       nameEnglish: 'An-Nas',         meaning: 'Mankind',                       ayahCount: 6,   revelationPlace: 'Makkah',   lastScore: 90),
];
