// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD52wXCXaaW34Aruvu-NzYWM72OlGKC-oo',
    appId: '1:639830542253:web:77b2b388c872abf79dc324',
    messagingSenderId: '639830542253',
    projectId: 'makharijpro-ai-9606e',
    authDomain: 'makharijpro-ai-9606e.firebaseapp.com',
    storageBucket: 'makharijpro-ai-9606e.firebasestorage.app',
    measurementId: 'G-72ZHRGPZR9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkfPAYOaWMlCo2lTLhietZda3eHO5c5OE',
    appId: '1:639830542253:android:bdc69a62c99b5bd19dc324',
    messagingSenderId: '639830542253',
    projectId: 'makharijpro-ai-9606e',
    storageBucket: 'makharijpro-ai-9606e.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD52wXCXaaW34Aruvu-NzYWM72OlGKC-oo',
    appId: '1:639830542253:web:1a2f4068a3edfd639dc324',
    messagingSenderId: '639830542253',
    projectId: 'makharijpro-ai-9606e',
    authDomain: 'makharijpro-ai-9606e.firebaseapp.com',
    storageBucket: 'makharijpro-ai-9606e.firebasestorage.app',
    measurementId: 'G-MT04FGQRNY',
  );
}
